//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comentario()
        {
            this.respuestas = new HashSet<respuesta>();
        }
    
        public long id { get; set; }
        public int id_documento { get; set; }
        public int id_grupo { get; set; }
        public int id_usuario { get; set; }
        public string comentario1 { get; set; }
        public System.DateTime fecha_publicacion { get; set; }
    
        public virtual documento documento { get; set; }
        public virtual grupos grupos { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuesta> respuestas { get; set; }
    }
}
