//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_relacionados
    {
        public int id_documento { get; set; }
        public int documento_relacionado1 { get; set; }
        public int documento_relacionado2 { get; set; }
    
        public virtual documento documento { get; set; }
        public virtual documento documento1 { get; set; }
        public virtual documento documento2 { get; set; }
    }
}
