//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_relacionados
    {
        public int id_documento { get; set; }
        public int documento_relacionado1 { get; set; }
        public int documento_relacionado2 { get; set; }
    
        public virtual documento documento { get; set; }
        public virtual documento documento1 { get; set; }
        public virtual documento documento2 { get; set; }
    }
}
