//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documento()
        {
            this.comentarios = new HashSet<comentario>();
            this.log_visitas_documentousuario = new HashSet<log_visitas_documentousuario>();
            this.libros = new HashSet<libro>();
            this.niveles = new HashSet<nivele>();
            this.documentos_curso = new HashSet<documentos_curso>();
        }
    
        public int id { get; set; }
        public int id_tipo { get; set; }
        public string url { get; set; }
        public Nullable<int> contador_visitas { get; set; }
        public string titulo { get; set; }
        public string descripcion_corta { get; set; }
        public string descripcion_detallada { get; set; }
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        public Nullable<bool> status { get; set; }
        public string imagen { get; set; }
        public string historial_version { get; set; }
        public Nullable<int> numero_version { get; set; }
        public int unidad { get; set; }
        public Nullable<int> capitulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario> comentarios { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual unidade unidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log_visitas_documentousuario> log_visitas_documentousuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<libro> libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nivele> niveles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentos_curso> documentos_curso { get; set; }
    }
}
