//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_curso
    {
        public int id_curso { get; set; }
        public int id_documento { get; set; }
        public bool visibilidad { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual documento documento { get; set; }
    }
}
