//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pimasEntities : DbContext
    {
        public pimasEntities()
            : base("name=pimasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<colegio> colegios { get; set; }
        public virtual DbSet<comentario> comentarios { get; set; }
        public virtual DbSet<curso> cursos { get; set; }
        public virtual DbSet<documento> documentos { get; set; }
        public virtual DbSet<documentos_curso> documentos_curso { get; set; }
        public virtual DbSet<documentos_profe> documentos_profe { get; set; }
        public virtual DbSet<grupos> grupos { get; set; }
        public virtual DbSet<libro> libros { get; set; }
        public virtual DbSet<log_visitas> log_visitas { get; set; }
        public virtual DbSet<log_visitas_cursousuario> log_visitas_cursousuario { get; set; }
        public virtual DbSet<log_visitas_documentousuario> log_visitas_documentousuario { get; set; }
        public virtual DbSet<nivele> niveles { get; set; }
        public virtual DbSet<notificacione> notificaciones { get; set; }
        public virtual DbSet<pais> paises { get; set; }
        public virtual DbSet<permiso> permisos { get; set; }
        public virtual DbSet<profesores_temporal> profesores_temporal { get; set; }
        public virtual DbSet<respuesta> respuestas { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tipo_colegio> tipo_colegio { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<unidade> unidades { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<documentos_relacionados> documentos_relacionados { get; set; }
        public virtual DbSet<documentos_usuario> documentos_usuario { get; set; }
        public virtual DbSet<transaccione> transacciones { get; set; }
        public virtual DbSet<articulo> articulos { get; set; }
        public virtual DbSet<carrito> carrito { get; set; }
        public virtual DbSet<categoria_articulo> categoria_articulo { get; set; }
        public virtual DbSet<estado_articulo> estado_articulo { get; set; }
        public virtual DbSet<estado_venta> estado_venta { get; set; }
        public virtual DbSet<tipos_pago> tipos_pago { get; set; }
        public virtual DbSet<transporte> transportes { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
        public virtual DbSet<ventas_articulos> ventas_articulos { get; set; }
    }
}
