//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuesta
    {
        public int id { get; set; }
        public long id_comentario { get; set; }
        public int id_usuario { get; set; }
        public string respuesta1 { get; set; }
        public System.DateTime fecha_publicacion { get; set; }
    
        public virtual comentario comentario { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
