//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuesta
    {
        public int id { get; set; }
        public long id_comentario { get; set; }
        public int id_usuario { get; set; }
        public string respuesta1 { get; set; }
        public System.DateTime fecha_publicacion { get; set; }
    
        public virtual comentario comentario { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
