//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccione
    {
        public int id_transaccion { get; set; }
        public int id_usuario { get; set; }
        public string transaccion { get; set; }
        public string especificacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
