//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma.Areas.PCD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int id { get; set; }
        public int id_articulo { get; set; }
        public string nombre_comprador { get; set; }
        public string nombre_receptor { get; set; }
        public int numero_comprador { get; set; }
        public int numero_receptor { get; set; }
        public string direccion { get; set; }
        public string horario { get; set; }
        public int cantidad { get; set; }
        public string tipo_entrega { get; set; }
        public string forma_pago { get; set; }
    
        public virtual Articulo Articulo { get; set; }
    }
}
